### PR TITLE
Fixed compilation for dmd 2.067

### PR DESCRIPTION
**Pull request by soarqin**
Since there will no functional changes after DMD 2.067b4, I think this patch would also work for DMD 2.067 final when it is out.

### CODE REVIEW

**Comment by NCrashed** [comment]
I use this PR branch until #30 persists

**Comment by o3o** [comment]
Thank you Anton !

**Comment by davispuh** [comment]
:+1:

**Comment by kiith-sa** [comment]
Thanks, merging.

**Pull request merged**
